### ISSUE TITLE
Future improvements

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#140]
## To realise by Patrick

- [x] [page 1] replace "Catch at sea" in the Title par "Catch at sea by Portuguese, Spanish, French, English and Irish fleets" in the title => Table of traduction ?
- [x] [page 1] display name of the geometry (not id), #153 
- [x] [page 1] display the prevalance (and not the prevalence class) when clicking on the geometry #153
- [ ] [page 1] translate 'prevalence'  and 'population status' in popup in the 4 languages
- [x] [Page1] replace basin_id by basin_name when clicking on the geometry #153
- [x] [page 1] change color for low prevalence: explorer dans "data-raw/bb-pgae1"  et changer code dans "R/mod_a_first_fct" pour `tm_ocean`
- [x] [page 1] change color for population status to avoid misinterpretation: explorer dans "data-raw/bb-pgae1"  et changer code dans "R/mod_a_first_fct" pour `tm_catchmment`

## Issue opened

- [ ] **15min** [page 1] Remove division from choices in page 1: https://github.com/inrae/diades.atlas/issues/152
- [ ] [Page 4] add a new period [1951-2000] to define  anthropogenic mortality #151
- [ ] [Page 4] increment of .1 rather 1 when using the mouse wheel #125

## Others

- [ ] [page 2] standardise with latin_name of the species (or everywhere local name if user prefer)  
- [ ] [All] add reference to reports, publication, ppt presentation for more details
- [ ] [All] add precautionary how-to-use to avoid in over-interpretation in the help popups
- [ ] [All] standardise name of species with latin_name (in italic) and local name to ease use for non-biologists. 
- [ ] [page 1] do not display geometries with "not recorded in the period" in catch at sea
- [ ] [Page 4] give order of magnitude for mortality in help popup
- [ ] [page 2} by default, present species by column

## Realised, to be merged in master

- [ ] [page 2] merge geometries to have the only 9 case studies #156 

## Realised  
- [x] [All] add a "for any feedback, contact  diades@inrae.fr" in the orange flag with the precautionary messages

**Comment by PMHLambert** [comment]
Done
[All] add a "for any feedback, contact [diades@inrae.fr](mailto:diades@inrae.fr)" in the orange flag with the precautionary messages
[page 1 replace "Catch at sea" par "Catch at sea by Portuguese, Spanish, French, English and Irish fleets" in the title
