### ISSUE TITLE
[4 - Future] Meta

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#23]
- [x] Fix list of all parameters that can be tested (see discussion on issue #19 )
- Set {waiter} and give information during model predictions
- Create map of predictions
![image](https://user-images.githubusercontent.com/21193866/102232686-b9307a80-3eef-11eb-81f9-72e7d8c30af1.png)

- [x] Exploration des scripts: https://github.com/inrae/diades.atlas/issues/19 
- [x] https://github.com/inrae/diades.atlas/issues/60
- [ ] https://github.com/inrae/diades.atlas/issues/7
- [x] https://github.com/inrae/diades.atlas/issues/71
- [x] https://github.com/inrae/diades.atlas/issues/89
- [ ] https://github.com/inrae/diades.atlas/issues/125
- [x] Autoriser les simulations avec rcp45

**Comment by statnmap** [comment]
Dans la branche issue-47, c'est ok, mais pas dans le 'main'.
Un problème de merge je pense.

main:
![image](https://user-images.githubusercontent.com/21193866/144263704-aa25853b-451f-4596-bd3d-591083db93e8.png)
issue-47
![image](https://user-images.githubusercontent.com/21193866/144263855-25652331-f983-4150-a2a1-f1c090aa1dcb.png)

- [ ] Ceci dit, à vérifier, mais il me semble qu'il ne faut choisir qu'une seule date et pas un range

**Comment by statnmap** [comment]
Close the Meta
