### ISSUE TITLE
[Meta] Remise en ordre

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#28]
- [x] Remettre les page dans le nouvel ordre (cf minutes)
- [x] Définir un fonctionnement commun entre Entrees / Sorties sur L'UI
- [ ] Page 2 . De JS => Shiny buttons
  - [ ]  Mettre les images dans le markdown d'aide et pas dans l'input
- [x] Page 1. Les graphs en cache, précalculés 
  - [x] Morceau de data spatiales dans la PostGIS + Code d'un tmap (Seb)

**Comment by statnmap** [comment]
Les pages sont dans le bon ordre. Présenté en réunion du 2021-11-26
