### ISSUE TITLE
[2- Ecosystem services] Meta

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#34]
- Filter on Case studies, species, ecosystem services
- Return a table
![image](https://user-images.githubusercontent.com/21193866/129004915-016ad673-4716-40eb-b6bf-25dcc38c2906.png)

- [ ]  https://github.com/inrae/diades.atlas/issues/7

**Comment by statnmap** [comment]
- [ ] INRAE propose la requête SQL qui permet de créer la table complète traduite pour les services écosystémiques: case_study, case_study_id, species, species_id, category, subcategory, category_id, subcategory_id, esvalue, esvalue_name
- [ ] ThinkR s'assure de n'afficher que les écosystèmes qui sont `publishable == TRUE`

**Comment by statnmap** [comment]
- [ ] Renommer en "Ecosystem services"

(Boutons) Sélecteurs

+ [ ] Mettre des "choose all"

+ [ ] Erreur dans les boutons : inverser le nom des deux boutons => Renommer le bouton "Select a case study" puis "Select a Ecosystem Service", 

+ [ ] Il faudra s'assurer que le Case study peut être partagé => colonne publishable == TRUE

+ [ ] Ecosystem services => Dans le tableau il y a des All subcategory. Il faudra trier par category name (Provisionning puis Regulating puis Cultural ) et subcategory (ALL SUBCATEGORIES en premier, trier par subcategory_id) 
`arrange(category_id puis subcategory)`

## (Output) CONSTRUCTION DU TABLEAU

- [ ] `v_ecosystemic_services` => `filter species_id == input$Species`, `case study == input$case_study`  et sur `Ecosystem Service (category & subcategory) == input$case_study`

On affiche la colonne esvalue_code

```
data.frame(
  fish_name,
  case_study_name, 
  sprintf("[%] %s", category, subcategory),
  esvalue_code
)
```

## Pouvoir faire un pivot_wider pour mettre un choix en colonne, mettre un sélecteur pour bouger ? 

- [ ] TODO Colin faire un POC là dessus sur le fait de pouvoir pivoter la table 

![diadestableau](https://user-images.githubusercontent.com/21193866/132469800-7df103b6-47d8-4e28-b1fe-eb9f3f818dd9.png)

**Comment by ColinFay** [comment]
#62 devrait close cette issue

**Comment by statnmap** [comment]
Page validée en réunion du 2021-11-26
