### ISSUE TITLE
Validation page 1

### ISSUE THREAD

**Issue by ColinFay** [inrae/diades.atlas#39]
# Validate 

Validation des modifications de la page 1.
(Vous pouvez cocher les cases et mettre un commentaire quand c'est bon)

https://connect.thinkr.fr/diades-main/

## Choose a species

+ [x] #41

+ [x] Sélectionner une espèce change le "conservation status" et la carte

## Conservation Status 

+ [x] Le "Conservation Status" se met à jour lorsque je change d'espèce

+ [x] Le "Conservation Status" est correct en fonction de l'espèce

## Source 

+ [x] Le bouton a été retiré

## Division / Rectangle 

+ [x] Un sélecteur permet de naviguer entre Division et rectangle

+ [x] Lorsque je change ce sélecteur, la carte se met à jour

## Carte

+ [x] La carte s'affiche

+ [x] La carte est correcte

+ [x] La carte se met à jour lorsque je change d'espèce ou de géométrie

+ [x] La carte est mise en cache : si je change entre division et rectangle une première fois, cela prend quelques secondes, si je refais le changement, c'est instantané. 

# TODO: 

Aujourd'hui, à l'ouverture, nous simplifions grandement la géométrie pour que le temps d'affichage de la carte soit raisonnable.  
Nous utilisons `rmapshaper::ms_simplify()` avec le réduction par défaut : On ne conserve que 5% des points. 
Tu verras que les contours sont encore acceptables, mais peut-être souhaiteriez-vous une réduction moindre. 

Si tu as accès à la base, ou à tes données directement, tu peux tester plusieurs valeurs de `keep` et observer avec {mapview} le résultat. Avec le script suivant si connecté à la base, sinon directement sur ta couche de polygones.

```r
catchment_geom <- sf::st_read(
 	con, 
	query =   "SELECT * FROM diadesatlas.v_basin vb"
) %>%
	rmapshaper::ms_simplify(keep = 0.05)

mapview::mapview(catchment_geom)
```
Une autre manière de bien se rendre compte du temps d'affichage c'est de transformer ta carte tmap en leaflet

```r
mon_tmap <- tm_shape(ma_couche) + tm_polygons()

# transformation en leaflet comme dans Shiny
tmap::tmap_leaflet(mon_tmap)
```

Sans `rmapshaper::ms_simplify()`, les cartes sont __très__ (trop?) longue à afficher (jusqu'à 1min30 dans certains cas). 
Blocage : `rmapshaper::ms_simplify()` prend plusieurs secondes et pourrait être fait en amont. 

+ [ ] Décider du pourcentage de réduction de la carte (Sur R, `keep` correspond au pourcentage de points conservées)
+ [ ] Faire la mise à jour dans la base SQL avec des geométries simplifiées pour les tables avec des géométries. 

# Tout est ok ?

+ [ ] Je ferme cette issue

**Comment by ColinFay** [comment]
TODO @statnmap 

Correction après retours de Patrick, à valider

+ [ ]  1, liste des espèces dans le bon ordre, réglé dans #45 
+ [ ] 2, déplacement status à côté de la carte, réglé dans #43 
+ [ ] 3, mettre en place le cache, réglé dans #46

**Comment by ColinFay** [comment]
@PMHLambert à valider sur https://connect.thinkr.fr/diades-main/ => "La carte est mise en cache"

**Comment by statnmap** [comment]
Page validée en réunion 2021-11-26.  
Une issue ouverte : https://github.com/inrae/diades.atlas/issues/67
