### ISSUE TITLE
[Livraisons] Meta

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#69]
Livraison:

- [x] Livrer le lien du package: https://github.com/inrae/diades.atlas
- [x] Livrer le Dockerfile
- [x] Livrer la doc pour l'installation: https://github.com/inrae/diades.atlas#readme
- [x] Livrer la doc pour la mise à jour des traductions: https://github.com/inrae/diades.atlas#readme
- [x] Le pkgdown: https://inrae.github.io/diades.atlas
- [x] Le rapport des tests unitaires - Doit être réalisé manuellement en local pour avoir accès à la database: https://inrae.github.io/diades.atlas/articles/tests_and_coverage.html
- [x] Livrer les instructions pour mettre à jour le guide d'utilisation et sa traduction

**Comment by statnmap** [comment]
Merci de valider que la documentation pour les items suivants est complète et compréhensible

- la mise en production sur vos serveurs: https://github.com/inrae/diades.atlas#readme
- L'utilisation des fonctions du package hors Shiny: https://inrae.github.io/diades.atlas/articles/aa-a-exploration_data.html
    - Dans "data-raw/aa-a-exploration_data.Rmd" 
    - Instructions évoquées dans le Readme https://github.com/inrae/diades.atlas#readme
 - La doc pour la mise à jour des traductions: https://github.com/inrae/diades.atlas#readme

**Comment by statnmap** [comment]
Validé en réunion du 9/02/2023
